relativeURLs = true
googleAnalytics = "UA-159072578-1"
title = "Simon Trenkle"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Simon Trenkle"

[markup] # needed to add html in .md
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "Institute of Labor Economics (IZA), IAB"
institution = ""
logo = "TrenkleS_cut3.jpg"
Email = "trenkle@iza.org"